spring.application.name=api-gateway
server.port=8080
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/developers/**,/apikeys/**

spring.cloud.gateway.server.webflux.routes[1].id=mock-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=ApiKeyGatewayFilter

spring.data.redis.host=localhost
spring.data.redis.port=6379

management.endpoints.web.exposure.include=*
#management.endpoint.prometheus.enabled=true
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=analytics-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer